FlashCardMania/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('flash_card.urls', 'flash_card'),
                     namespace='flash_card')),
    path('accounts/', include('django.contrib.auth.urls'))
]

flash_card/urls.py
from django.contrib import admin
from django.urls import path, include
from flash_card import views

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile_page, name='profile_page'),
    path('create/category/', views.create_category, name='create_category'),
    path('create/card/', views.create_card, name='create_card'),
    path('create/game/', views.create_game, name='game_form'),
    path('card/selection/', views.card_view_selection, name='card_selection'),
    path('card/list/', views.view_all_cards, name='card_list'),
    path('card/<int:pk>/', views.card_view, name='card_view'),
    path('game/card/', views.game_view, name='game_card_view'),
]

flash_card/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils import timezone


class Category(models.Model):
    ''' A category of FlashCards e.g. Spanish'''

    name = models.CharField(max_length=50,
                            help_text='Name of category.')
    created_by = models.ForeignKey(User,
                                   on_delete=models.SET_NULL,
                                   null=True,
                                   blank=True)

    def __str__(self):
        return self.name


class FlashCard(models.Model):
    ''' Represents a single flash card.'''

    LEVELS = tuple((x, x) for x in range(1, 11))

    TYPES = (
        ('s', 'Short'),
        ('l', 'Long'),
    )

    COLOURS = {
        1: '#d7ffbb',  # green
        2: '#AAFFEE',  # aqua
        3: '#cfe3ff',  # blue
        4: '#d4d0ff',  # lilac
        5: '#ffc0cb',  # pink
        6: '#ff7169',  # red
        7: '#FFD394',  # orange
        8: '#FDFD96',  # yellow
        9: '#FFFFFF',  # white
        10: '#c0c0c0'  # silver
    }

    created_by = models.ForeignKey(User,
                                   on_delete=models.SET_NULL,
                                   null=True,
                                   blank=True)
    question = models.CharField(max_length=200)
    answer = models.CharField(max_length=200)
    category = models.ForeignKey(Category,
                                 on_delete=models.SET_NULL,
                                 null=True,
                                 blank=True,
                                 help_text='category in which the flash card belongs.')
    image = models.ImageField(upload_to='tmp/',
                              blank=True,
                              null=True,
                              help_text='image representation of the question.')
    audio = models.FileField(upload_to='tmp/',
                             blank=True,
                             null=True,
                             help_text='audio representation of the question.')
    level = models.IntegerField(choices=LEVELS,
                                help_text='difficulty level.')
    colour = models.CharField(max_length=20,
                              null=True,
                              blank=True,
                              help_text='colour of flash card.')
    type = models.CharField(
        max_length=20,
        choices=TYPES,
        help_text='short or long charactered card.'
    )

    def __str__(self):
        return f'{self.pk}'

    def save(self, *args, **kwargs):
        # set colour based upon level
        colour = self.COLOURS.get(int(self.level))
        self.colour = colour
        super().save(self, *args, **kwargs)


class GameInstance(models.Model):
    ''' Instance of a flash card game.'''

    TYPES = (
        ('c', 'Multiple Choice'),
        ('w', 'Writing')
    )

    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          editable=False, unique=True)
    participant = models.ForeignKey(User,
                                    on_delete=models.SET_NULL,
                                    null=True,
                                    blank=True)
    date = models.DateTimeField(null=True, blank=True, default=timezone.now())
    cards = models.ManyToManyField(FlashCard,
                                   help_text='all cards used in game.')
    score = models.IntegerField(
        validators=[
            MaxValueValidator(100),
            MinValueValidator(1)
        ],
        help_text='percentage of correct answers in game.'
    )
    type = models.CharField(
        max_length=50,
        choices=TYPES,
        blank=True,
        help_text='type of game played'
    )

    def __str__(self):
        return f'{self.participant.username} - {self.date}'

flash_card/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Category, FlashCard


class CategoryForm(forms.Form):
    name = forms.CharField(max_length=200)
    template_name = 'flash_card/generic_form.html'


class CardCreationForm(forms.Form):
    question = forms.CharField(max_length=200)
    answer = forms.CharField(max_length=200)
    level = forms.ChoiceField(choices=FlashCard.LEVELS)
    type = forms.ChoiceField(choices=FlashCard.TYPES)
    image = forms.ImageField(required=False)
    audio = forms.FileField(required=False)
    category = forms.ModelChoiceField(queryset=Category.objects.all())
    template_name = 'flash_card/generic_form.html'


class CardViewForm(forms.Form):
    USERS = tuple((x.username, x) for x in User.objects.all())
    CATEGORIES = tuple((x.name, x) for x in Category.objects.all())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for key in self.fields:
            self.fields[key].required = False

    category = forms.MultipleChoiceField(choices=CATEGORIES)
    level = forms.MultipleChoiceField(choices=FlashCard.LEVELS)
    users = forms.MultipleChoiceField(choices=USERS)
    type = forms.MultipleChoiceField(choices=FlashCard.TYPES)

    def clean(self):
        ''' If nothing selected for a field then return all for that field.'''
        d = {'category': [x.name for x in Category.objects.all()],
             'level': [x[0] for x in FlashCard.LEVELS],
             'users': [x.username for x in User.objects.all()],
             'type': [x[0] for x in FlashCard.TYPES]}
        for key, value in self.cleaned_data.items():
            if value:
                d[key] = value
        return d

flash_card/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpRequest

from .forms import CategoryForm, CardCreationForm, CardViewForm
from .qs2table import result_as_table
from .models import FlashCard, Category, GameInstance

import random


def index(request):
    return render(request=request,
                  template_name='flash_card/index.html')


@login_required
def profile_page(request):
    ''' Detailed view of a users Profile.'''
    return render(request=request,
                  template_name='flash_card/profile_page.html',
                  context={'user': request.user})


def card_filtering(request):
    ''' Filter cards based upon form and return cards.'''
    form = CardViewForm(request.POST)
    if form.is_valid():
        category = form.cleaned_data['category']
        level = form.cleaned_data['level']
        users = form.cleaned_data['users']
        card_type = form.cleaned_data['type']
        cards = FlashCard.objects.filter(category__name__in=category,
                                         level__in=level,
                                         created_by__username__in=users,
                                         type__in=card_type)
        return cards


def card_view_selection(request):
    ''' Produces a card table based off of user
        inputted filtering criteria.
    '''
    if request.method == 'POST':
        cards = card_filtering(request)
        columns = ['id', 'question', 'answer', 'level', 'type']
        table = result_as_table(cards, fieldnames=columns)
        return render(request=request,
                      template_name='flash_card/card_list.html',
                      context={'table': table})
    else:
        return render(request=request,
                      template_name='flash_card/generic_form.html',
                      context={'form': CardViewForm(),
                               'title': 'Card Selection'})


def view_all_cards(request):
    ''' Produces a table of all cards in the database.'''
    all_cards = FlashCard.objects.all()
    columns = ['id', 'question', 'answer', 'level', 'type']
    table = result_as_table(all_cards, fieldnames=columns)
    return render(request=request,
                  template_name='flash_card/card_list.html',
                  context={'table': table})


def card_view(request, pk):
    ''' A detailed view of a card.'''
    card = FlashCard.objects.get(pk=pk)
    return render(request=request,
                  template_name='flash_card/full_card_view.html',
                  context={'card': card})


@login_required
def create_category(request):
    ''' Create a Category model.'''
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            if Category.objects.filter(name=name.upper()):
                return render(request=request,
                              template_name='flash_card/result.html',
                              context={'title': 'Failure',
                                       'message': 'Category object already exists.'})
            category = Category(name=name.upper(), created_by=request.user)
            category.save()
            return render(request=request,
                          template_name='flash_card/result.html',
                          context={'title': 'Success',
                                   'message': 'Category created successfully.'})
    else:
        return render(request=request,
                      template_name='flash_card/generic_form.html',
                      context={'form': CategoryForm(),
                               'title': 'Category Creation'})


@login_required
def create_card(request):
    ''' Create a Card model.'''
    if request.method == 'POST':
        form = CardCreationForm(request.POST, request.FILES)
        if form.is_valid():
            question = form.cleaned_data['question']
            answer = form.cleaned_data['answer']
            level = form.cleaned_data['level']
            card_type = form.cleaned_data['type']
            image = form.cleaned_data['image']
            audio = form.cleaned_data['audio']
            category = form.cleaned_data['category']
            card = FlashCard(question=question,
                             answer=answer,
                             level=level,
                             type=card_type,
                             image=image,
                             audio=audio,
                             category=category,
                             created_by=request.user)
            card.save()
            return render(request=request,
                          template_name='flash_card/result.html',
                          context={'title': 'Success',
                                   'message': 'Card created successfully.'})
        else:
            return render(request=request,
                          template_name='flash_card/result.html',
                          context={'title': 'Failure',
                                   'message': form.errors})
    else:
        return render(request=request,
                      template_name='flash_card/generic_form.html',
                      context={'form': CardCreationForm(),
                               'title': 'Card Creation'})


# def get_random_cards(cards, num=10):
#     ''' Get 10 or less objects from a Card QuerySet.'''
#     random_cards = []
#     n = num if cards.count() > num else cards.count()
#     for _ in range(n):
#         card = random.choice(cards)
#         random_cards.append(card)
#     return random_cards


@login_required
def create_game(request):
    ''' Game form to select specific cards for game session.'''
    if request.method == 'POST':
        if not request.session.get('cards'):
            cards = card_filtering(request)
        else:
            cards = FlashCard.objects.filter(pk__in=request.session['cards'])
        # add cards pk list value to session
        request.session['cards'] = list(cards.values_list('pk', flat=True))
        return redirect('flash_card:game_card_view')
    else:
        return render(request=request,
                      template_name='flash_card/generic_form.html',
                      context={'form': CardViewForm(),
                               'title': 'Game Card Selection'})


@login_required
def game_view(request):
    ''' View individual cards in game.'''
    cards = request.session['cards']
    if not cards:
        # game completion page
        return render(request=request,
                      template_name='flash_card/result.html',
                      context={'title': 'Game Complete',
                               'message': 'You have exhausted all cards'})
    # get random card pk from cards in session
    card_pk = random.choice(request.session['cards'])
    cards.remove(card_pk)
    request.session['cards'] = cards
    card = FlashCard.objects.get(pk=card_pk)
    return render(request=request,
                  template_name='flash_card/game_card_view.html',
                  context={'card': card})

flash_card/templates/flash_card/base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  {% block title %}
    <title>Flash Mania</title>
  {% endblock %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'flash_card/styles.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/components/sidebar.js"></script>
  <script type="text/javascript">
    function main() {
    $('.ui.left.sidebar').sidebar({
        dimPage: false,
        transition: 'push',
        exclusive: false,
        closable: false
    });

    $('.ui.left.sidebar')
        .sidebar('attach events', '#hide-sidebar');
    $('.ui.left.sidebar')
        .sidebar('attach events', '#show-sidebar');
    }
    $(document).ready(main);
  </script>
  {% block script %}
  {% endblock %}
</head>

<body>
  {% block sidebar %}
    <div class="ui left vertical menu overlay sidebar" >
      <div id="hide-sidebar" class="button">
        <image src="https://cdn3.iconfinder.com/data/icons/32-fufficon/32/32x32_fluffy-03-24.png">
      </div>
      <a class="item" style="color:black" href="{% url 'flash_card:index' %}">Home</a>
      {% if user.is_authenticated %}
        <div class="item">
          <div class="header">{{ user.get_username }}</div>
          <div class="menu">
            <a class="item" href="{% url 'flash_card:profile_page' %}">Profile</a>
            <a class="item" href="{% url 'logout'%}">Logout</a>
          </div>
        </div>
      {% else %}
	      <a class="item" href="{% url 'login'%}">Login</a>
	    {% endif %}
      {% if user.is_authenticated %}
        <div class="item">
          <div class="header">Game</div>
          <div class="menu">
            <a class="item" href="{% url 'flash_card:game_form' %}">Play</a>
          </div>
        </div>
      {% endif %}
      <div class="item">
        <div class="header">Cards</div>
        <div class="menu">
          <a class="item" href="{% url 'flash_card:card_list' %}">List Cards</a>
          <a class="item" href="{% url 'flash_card:card_selection' %}">Filter Cards</a>
        {% if user.is_authenticated %}
          <a class="item" href="{% url 'flash_card:create_card' %}">Create Card</a>
          <a class="item" href="{% url 'flash_card:create_category' %}">Create Category</a>
        {% endif %}
        </div>
      </div>
    </div>
  {% endblock %}
  <div class="pusher">
    <div id="show-sidebar" class="button">
      <image src="https://cdn3.iconfinder.com/data/icons/32-fufficon/32/32x32_fluffy-03-24.png">
    </div>
    {% block content %}
    {% endblock %}
  </div>
</body>

</html>

flash_card/templates/flash_card/card_list.html
{% extends 'base_generic.html' %}

{% block content %}

<div class="ui main text container centre aligned">
  <div class="content">
    {{ table | safe }}
  </div>
</div>

{% endblock %}

flash_card/templates/flash_card/card_view.html
{% extends 'base_generic.html' %}

{% block content %}

<div class="ui main text container centre aligned card" style={{style}} >
  <b><font size="1">
    &nbsp
    {{ card.category.name.title }}&nbsp&nbsp
    {{ card.level }}&nbsp&nbsp
  </font></b>
  <div class="center aligned content">
      <h2 class="ui header">Card Detail</h2><br/>
      <div class="center aligned description">
        <p>Question:  {{ card.question }}</p>
        <p>Answer:  {{ card.answer }}</p>
    </div>
  </div>
  <div class="extra content">
    <font size="1">
      Type: {{ card.get_type_display }}&nbsp&nbsp
    </font>
    {% if card.image %}
      <font size="1">
        Image: Yes &nbsp&nbsp
      </font>
    {% else %}
      <font size="1">
        Image: No &nbsp&nbsp
      </font>
    {% endif %}
    {% if card.audio %}
      <font size="1">
        Audio: Yes &nbsp&nbsp
      </font>
    {% else %}
      <font size="1">
        Audio: No &nbsp&nbsp
      </font>
    {% endif %}
  </div>
</div>

{% endblock %}

flash_card/templates/flash_card/full_card_view.html
{% extends 'generic_card_view.html' %}

{% block answer %}
<p>Answer:  {{ card.answer }}</p>
{% endblock %}

flash_card/templates/flash_card/game_card_view.html
{% extends 'generic_card_view.html' %}

{% block script %}

<script type="text/javascript">
// toggle answer appearance in flash card
function toggleAnswer() {
  var x = document.getElementById("show-answer");
  if (x.style.display === "none") {
      x.style.display = "block";
  } else {
      x.style.display = "none";
  }
} 
</script>

{% endblock %}


{% block answer %}
<p id="show-answer" style="display:none;">
  Answer:  {{ card.answer }}
</p>
{% endblock %}

{% block buttons %}

<button onclick="toggleAnswer()" class="ui primary button">
  Answer
</button>

<a href="{% url 'flash_card:game_card_view' %}" class="ui button">
  Next Card
</a>
{% endblock %}

flash_card/templates/flash_card/generic_card_view.html
{% extends 'base_generic.html' %}


{% block content %}

<div class="ui main text container centre aligned">
  <div class="ui main text container card" style="background-color:{{card.colour}};min-width:400px" >
    <b><font size="1">
      &nbsp
      {{ card.category.name.title }}&nbsp&nbsp
      {{ card.level }}&nbsp&nbsp
    </font></b>
    <div class="center aligned content">
        <h2 class="ui header">Card Detail</h2><br/>
        <div class="center aligned description">
          <p>Question:  {{ card.question }}</p>
          {% block answer %}
          {% endblock %}
      </div>
    </div>
    <div class="extra content">
      <font size="1">
        Type: {{ card.get_type_display }}&nbsp&nbsp
      </font>
      {% if card.image %}
        <font size="1">
          Image: Yes &nbsp&nbsp
        </font>
      {% else %}
        <font size="1">
          Image: No &nbsp&nbsp
        </font>
      {% endif %}
      {% if card.audio %}
        <font size="1">
          Audio: Yes &nbsp&nbsp
        </font>
      {% else %}
        <font size="1">
          Audio: No &nbsp&nbsp
        </font>
      {% endif %}
    </div>
  </div>

  {% block buttons %}
  {% endblock %}
</div>
{% endblock %}

flash_card/templates/flash_card/generic_form.html
{% extends 'base_generic.html' %}

{% block content %}

<div class="ui main text container centre aligned">
  <div class="content">
      <form class='ui form segment' method="post">{% csrf_token %}
        <h1>{{ title }}</h1>
        {{ form.as_p }}
        <input type="submit" value="Save">
      </form>
  </div>
</div>

{% endblock %}

flash_card/templates/flash_card/index.html
{% extends 'base_generic.html' %}

{% block content %}

<div class="ui three column stackable grid">
<div class="two wide column">
</div>
<div class="column">
    <h2>Flash Card Mania</h2>
    <p>Want to learn more about History but struggling to remember the date of important events? Are you learning French but are confusing the word sex with vomit?</p>
    <p>You can solve all these problems with <strong>Flash Cards</strong>!</p>
    <p>Sign up, create and learn those hard to remember facts with our <em>engaging</em> games and scoreboard!</p>
    <p><small>Check out our current selection of <a href="{% url 'flash_card:card_list' %}">cards</a> and categories.</small></p>
</div>
<div class="ui three column stackable padded middle aligned centered color grid">
      <div class="red column">Law</div>
      <div class="orange column">Physics</div>
      <div class="yellow column">Literature</div>
      <div class="olive column">Philosophy</div>
      <div class="green column">Language</div>
      <div class="teal column">Economics</div>
      <div class="blue column">Biology</div>
      <div class="violet column">Chemistry</div>
      <div class="purple column">History</div>
      <div class="pink column">Statistics</div>
      <div class="brown column">Archaeology</div>
      <div class="grey column">Psychology</div>
      <div class="black column">Flash Cards</div>
    </div>
</div>

{% endblock %}

flash_card/templates/flash_card/profile_page.html
{% extends 'base_generic.html' %}

{% block content %}

<div class="ui main text container centre aligned">
  <div class="content">
    <div class="ui raised very padded text container segment">
      <h2 class="ui header">Profile Details</h2>
      <div class="description">
        First Name:  {{ user.first_name }}<br/>
        Last Name:  {{ user.last_name }}<br/>
        User Name: {{ user.username }}<br/>
        Email: {{ user.email }}<br/>
      </div>
    <div class="description">
  </div>
  </div>
</div>

{% endblock %}

flash_card/templates/flash_card/result.html
{% extends 'base_generic.html' %}

{% block content %}

<div class="ui main text container centre aligned">
  <div class="content">
    <div class="ui raised very padded text container segment">
      <h2 class="ui header">{{ title }}</h2>
      <div class="description">{{ message }}</div>
    </div>
  </div>
</div>

{% endblock %}